### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by WangZhaoxue** [zhreshold/decord#10]
CMakeFiles/decord.dir/build.make:62: recipe for target 'CMakeFiles/decord.dir/src/runtime/c_runtime_api.cc.o' failed
make[2]: *** [CMakeFiles/decord.dir/src/runtime/c_runtime_api.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/decord.dir/all' failed
make[1]: *** [CMakeFiles/decord.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zhreshold** [comment]
might be related to compiler or ffmpeg.
You can now use pip install decord instead.

**Comment by sixyang** [comment]
> might be related to compiler or ffmpeg. You can now use pip install decord instead.

can I use gpu with pip download?
