### ISSUE TITLE
decord compiled with ffmpeg 4 failed to load videos processed by ffmpeg 2

### ISSUE THREAD

**Issue by kennymckormick** [zhreshold/decord#12]
Hi zhreshold,
    I compiled the latest decord(0.3.1) with ffmpeg 4.2(libavcodec 58.* ), and when I read video (processed with ffmpeg2, libavcodec 56.* ) with the compiled decord, it throws out the error:

    avcodec_send_packet(def ctx.get(), pkt.get()) >= 0 (-11 vs. 0) thread worker: error sending packet

    Would you please check if it also happends on your system?

**Comment by zhreshold** [comment]
Would you mind share the video and the reproduciable script?
