### ISSUE TITLE
module 'decord' has no attribute 'video_reader'

### ISSUE THREAD

**Issue by nicholasguimaraes** [zhreshold/decord#18]
Hello I have decord 0.3.3 installed but I believe something went wrong with the installation.

I'm trying to run a code snippet but I can't use one of decord's most valuable modules. 
"""
import decord
video_name = 'boxing_test.mp4'
data = decord.VideoReader(video_name)
frames = data.get_batch(range(124,156))
print(frames.shape)
"""

When I run the code above I get this error;
module 'decord' has no attribute 'VideoReader'

I pip installed decord. 

How can I solve this problem?

**Comment by zhreshold** [comment]
You probably installed an empty decord already somewhere, try delete anything related to decord in site-packages in your python directory, and reinstall please.

**Comment by xuweidongkobe** [comment]
hi, @nicholasguimaraes I have the same problem, can you fix it?
